### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by alexander-akait** [nfroidure/gulp-ttf2woff2#1]
@nfroidure some strange error. Code:

``` javascript
       gulp.src(directory.src, {
                base: process.cwd()
            })
                .pipe($.plumber(options.build.plumber))
                .pipe($.svg2ttf({
                    clone: true,
                    timestamp: Date.now()
                }).on('error', function (error) {
                    return done(error);
                }))
                .pipe($.ttf2eot({
                    clone: true
                }).on('error', function (error) {
                    return done(error);
                }))
                .pipe($.ttf2woff({
                    clone: true
                }).on('error', function (error) {
                    return done(error);
                }))
                .pipe($.ttf2woff2({
                    clone: true
                }).on('error', function (error) {
                    return done(error);
                }))
                .pipe($.flatten())
                .pipe(gulp.dest(directory.dest));
```

$ - alias for gulp-load-plugins
src = /fonts/*.svg

**Comment by nfroidure** [comment]
In order to reproduce the bug, run this and check that the outputted ttf file reproduce the Segmentation fault when passing it to ttf2woff2:

```
gulp.src(directory.src, {
                base: process.cwd()
            })
                .pipe($.plumber(options.build.plumber))
                .pipe($.svg2ttf({
                    clone: true,
                    timestamp: Date.now()
                }).on('error', function (error) {
                    return done(error);
                }))
                .pipe(gulp.dest(directory.dest));
```

If it does, please transmit it for debugging.

Also, can you say if you use the native or the emscripten wrapper ? You can easily know this by removing every line except this one https://github.com/nfroidure/ttf2woff2/blob/master/src/index.js#L4 in your node_modules/ directory and see if the problem persist.

**Comment by nfroidure** [comment]
Possibly related to failing build https://travis-ci.org/nfroidure/gulp-iconfont/builds/71533143

**Comment by vsorrokin** [comment]
Same problem here. This error happens on a big set of fonts (around 20).

**Comment by alexander-akait** [comment]
@vsorrokin around 20 what?

**Comment by vsorrokin** [comment]
@evilebottnawi  Around 20 source font files

**Comment by alexander-akait** [comment]
@vsorrokin i have this error with 1 source font

**Comment by exdeniz** [comment]
I have this error too with 1 source or many fonts.

**Comment by droplab** [comment]
+1 I'm having this error too. Although it seems to depend on the fonts. When I removed certain fonts from the group there was no segfault. I wonder if the filesize of a font is a factor here.

**Comment by nfroidure** [comment]
Please read my answer instead of +1ing.

> If it does, please transmit it for debugging.

**Comment by nfroidure** [comment]
Just released a new version using nan, please try it since it could also have solved some memory management issues.

If it doesn't, please try to convert your font with the original woff2 converter available here and see if the error also happen. In ths case, please report the issue in that repo. https://github.com/google/woff2

If it works, please reopen the issue in the ttf2woff2 projects were the problem really sits https://github.com/nfroidure/ttf2woff2 and refer to this issue.
