### ISSUE TITLE
(node:14808) V8: PATH\node_modules\ttf2woff2\jssrc\ttf2woff2.js:3 Invalid asm.js: Invalid member of stdlib

### ISSUE THREAD

**Issue by thisVioletHydra** [nfroidure/gulp-ttf2woff2#7]
```
src(`${inDevApps}/fonts/Ubuntu/*.ttf`, { allowEmpty: true }),
  _run.ttf2woff(),
dest(`${inDevApps}/fonts/Ubuntu/`)
```
fonts created but error infuriates me

**Comment by davideberlein** [comment]
I have the same problem, anything we can do?

**Comment by adammo14** [comment]
I'm having the same issue, very frustrating.

**Comment by nfroidure** [comment]
I guess that a rebuild of the JS fallback with a recenter Emscripten version inside the `ttf2woff2` module may address this issue. Any PR is welcome.

**Comment by thisVioletHydra** [comment]
⚰️ rip

**Comment by dheeyi** [comment]
any suggestions in order to solve this error?

**Comment by cport1** [comment]
> any suggestions in order to solve this error?

downgrade to node 12.16.1 and it works again

**Comment by swevans** [comment]
It's been a bit, but I thought I'd throw out an answer I found. If you npm install ttf2woff2 (>= 4.0.0) then the error disappears. It looks like the gulp version (and fontmin) are using an old version of ttf2woff2.

**Comment by patricknelson** [comment]
@swevans adding `ttf2woff2@^4.0.4` in the root `package.json` doesn't seem to address it for me, but my guess is maybe because it's not used as a peer dependency. How exactly did you fix the problem this way? It still seems to trigger the error for me.

**Edit:** Never mind, for me the easier fix was to just transition from `gulp-iconfont@^10.0.3` to `gulp-iconfont@^11.0.1` (which was that I was using that referenced this package). Please excuse my silly question 😄
